language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "djon-wick-github"
    token:
      secure: ad78a16ac90d4153c6eda9a23e52afff4d805488

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
email: false
